name: Nahogram APK Üretimi

on:
  push:
    branches: [ "main" ] 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Kodları Çek
        uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Kivy ve Buildozer Kurulumu
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.33 virtualenv
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev libssl-dev git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libsqlite3-dev sqlite3

      - name: Dosya Adını Düzelt (Hayat Kurtaran Hamle)
        run: mv Nahogram.py main.py

      - name: Buildozer ile APK Üret!
        run: buildozer -v android debug

      - name: Üretilen APK'yı Bana Ver
        uses: actions/upload-artifact@v3
        with:
          name: Nahogram_APK
          path: bin/*.apk
